server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/docdb
    username: docuser
    password: docpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: redis
    port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG 