groups:
  - name: user-service-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{application="user-service",status=~"5.."}[5m]) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected in user-service"
          description: "More than 1 error per second in user-service over the last 5 minutes." 