server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/docdb
    username: docuser
    password: docpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG 